name: Build images and copy image to docker
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
jobs:
  build-images:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      # - name: Save version info
      #   run: |
      #     git describe --tags > VERSION 
      # - name: Translate
      #   run: |
      #     python ./i18n/translate.py --repository_path . --json_file_path ./i18n/en.json

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y nodejs npm
      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
          
      - name: Login to Docker Registry
        run: | 
         docker version
         # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          
      - name: Set DOCKER_REPO_TAGGED based on branch or tag
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          fi    
         # 使用Dockerfile构建镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # file: ./Dockerfile
          platforms: linux/amd64
          tags: |
            registry.cn-hangzhou.aliyuncs.com/aabao/new-api:${{env.IMAGE_TAG}}
            registry.cn-hangzhou.aliyuncs.com/aabao/new-api:latest
